# ~/.bash_profile: executed by bash(1) for login shells.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/login.defs
#umask 022

# include .bashrc if it exists
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

#===============================================================
# Define some colors first:
red='\e[0;31m'
RED='\e[1;31m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m'              # No Color
# --> Nice. Has the same effect as using "ansi.sys" in DOS.

#-------------------
# Personnal Aliases
#-------------------

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
# -> Prevents accidentally clobbering files.
alias mkdir='mkdir -p'

alias h='history'
alias j='jobs -l'
alias r='rlogin'
alias which='type -all'
alias ..='cd ..'
alias path='echo -e ${PATH//:/\\n}'
alias du='du -kh'
alias df='df -kTh'

# The 'ls' family (this assumes you use the GNU ls)
alias la='ls -Al'           # show hidden files
alias ls='ls -hF --color'	# add colors for filetype recognition
alias ll='ls -l'            # list files
alias lx='ls -lXB'          # sort by extension
alias lk='ls -lSr'          # sort by size
alias lc='ls -lcr'          # sort by change time
alias lu='ls -lur'          # sort by access time
alias lr='ls -lR'           # recursive ls
alias lt='ls -ltr'          # sort by date
alias lm='ls -al |more'     # pipe through 'more'
alias tree='tree -Csu'      # nice alternative to 'ls'

# emacs in no-window mode
alias emacs="emacs -nw"

# User specific aliases and functions
alias almostFinished="echo '************************************';
                      echo 'Finished Steps:' ;
                      grep -r --include '*.log' 'cpu time' ~/*
                     "
alias finished="echo '************************************';
                echo 'Finished Computations:' ;
                ls -R ~/ | grep '\.e' -c ;
                ls -R ~/ | grep '\.e'
               "

alias nbtour="echo '************************************';
              echo 'Nombre de Tours :' ;
              grep -r --include '*.log' -c Predicted ~/*
             "

alias count="echo '************************************';
             echo 'Number of YESs:' ;
             grep -r --include '*.log' -c YES ~/*
            "

alias encours="echo '************************************';
               echo 'Running Computations: ' ;
               squeue -u enicolas ;
               echo '************************************';
               echo 'Total Number of Computations:' ;
               squeue -u enicolas | grep enicolas -c
              "

alias lowFreq="echo '************************************';
               echo 'Three Lowest Frequencies: ' ;
               echo '************************************';
               grep -r --include '*.log' -A6 Harmonic ~/*
              "

alias vectors="echo '************************************';
               echo 'Computed Vectors:';
               grep -r --include '*.log' -E 'vectors produced|vectors were produced' ~/* | sed 's/\(produced\).*/\1/g'
              "

alias warning="echo '************************************';
               echo 'Warning Produced: ' ;
               grep -r --include '*.log' Warning ~/*
              "

alias predictions="find /home/enicolas -name '*.log' -exec sh -c 'echo; echo {}; grep Predicted -B5 {} | tail -6' \;"

alias username="encours nbtour count almostFinished finished"

alias complet="username vectors warning lowFreq"
