#.bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# Setup path
export PATH=$PATH:$HOME/.local/bin

# Intel compilers + OpenMPI Library
module load intel/17.0
module load openmpi/intel/2.0.1

# Gaussian
module load gaussian/g09
source ${g09root}/g09/bsd/g09.profile

# ADF
module load adf/2016.102-openmpi

# Python
module load python/3.5.3
