#!/usr/bin/env bash

# ##################################################
# Setup account for easier computing on OCCIGEN cluster
#

# Safety conversion
dos2unix ./*

# Create directories
mkdir -p ~/.local/bin
mkdir -p "$SCRATCHDIR"/adf
mkdir -p "$SCRATCHDIR"/gaussian/rwf
mkdir -p "$SCRATCHDIR"/orca

# Create shortcuts for the scratch
ln -sTf "$SCRATCHDIR" ~/scratch
ln -sTf "$SCRATCHDIR"/adf ~/scratchADF
ln -sTf "$SCRATCHDIR"/gaussian ~/scratchGaussian
ln -sTf "$SCRATCHDIR"/orca ~/scratchOrca

# Retrieve email and name from user
echo -n "Enter your email address and press [ENTER]: "
read -r mail
echo -n "Enter your first name and press [ENTER]: "
read -r firstname

# Copy files and change emails and firstnames when necessary
sed -e "s/user@server.org/${mail}/" < forward > ~/.forward
sed -e "s/username/${firstname}/" < bash_profile > ~/.bash_profile
cp -f bashrc ~/.bashrc
cp -f emacs ~/.emacs
sed -e "s/user@server.org/${mail}/" < subadf.py > ~/.local/bin/subadf.py
sed -e "s/user@server.org/${mail}/" < subg16.py > ~/.local/bin/subg16.py
sed -e "s/user@server.org/${mail}/" < suborca.py > ~/.local/bin/suborca.py

# Change permissions
chmod +x ~/.local/bin/subadf.py
chmod +x ~/.local/bin/subg16.py
chmod +x ~/.local/bin/suborca.py

echo "Your account was set up. You should log off and back on to make sure"
echo "everything works."
echo ""
echo "Report every problem to Emmanuel Nicolas (emmanuel.nicolas -at- cea.fr)"
